import { BASIS_WORD } from '../../present/parts.ts';
import type { SessionSectionView } from '../../present/session.ts';
import { html, type Raw } from '../html.ts';

export const sessionMarkup = (view: SessionSectionView, actionError: string | null = null): Raw => {
  if (view.mode === 'non-local') return html`<div class="ws ws-session" id="ws" data-presentation="session" data-mode="non-local" style="height:${view.height}px"><div class="ws-line ws-nonlocal">${view.phase}</div></div>`;
  const value = view.value, scope = view.scope, alert = view.alert;
  return html`<div class="ws ws-session" id="ws" data-presentation="session" data-mode="summary" style="height:${view.height}px"><div class="ws-line ws-heading"><span class="ws-phase" data-tone="${view.tone}" title="${view.phase}">${view.phase}</span>${value ? html`<span class="ws-rate" data-basis="${value.basis}">${value.text}${value.unit ? html` <small>${value.unit}</small>` : ''}${value.basis !== 'reported' ? html` <small class="basis">${BASIS_WORD[value.basis]}</small>` : ''}</span>` : ''}</div>${view.model ? html`<div class="ws-line ws-model-line"><span class="ws-label">Model</span><span class="ws-model" translate="no" title="${view.modelTitle ?? view.model}">${view.model}</span></div>` : ''}${scope || view.age ? html`<div class="ws-meta">${scope ? html`<span class="ws-scope" data-attr="${scope.attr}" title="${scope.detail ? `${scope.text} · ${scope.detail}` : scope.text}" aria-label="${scope.detail ? `${scope.text} · ${scope.detail}` : scope.text}">${scope.text}</span>` : ''}${view.age ? html`<span class="ws-age">${view.age}</span>` : ''}</div>` : ''}${view.note ? html`<div class="ws-note" title="${view.note}">${view.note}</div>` : ''}${alert ? html`<div class="ws-line ws-alert-row"><span class="ws-label" title="${alert.label}">${alert.label}</span><span class="ws-alert-value" data-severity="${alert.severity}">${alert.value}${alert.more ? html` <small>+${alert.more} more</small>` : ''}</span></div>` : ''}<div class="ws-actions"><button type="button" class="ws-details" data-action="open-scope">Open MLX Scope</button>${view.cancelMeasurement ? html`<button type="button" class="ws-details" data-action="next-cancel">Cancel measurement</button>` : ''}</div>${actionError ? html`<p class="ws-action-error" id="ws-action-error" role="status">${actionError}</p>` : ''}</div>`;
};
