import type { SessionSectionView } from '../../present/session.ts';
import { html, type Raw } from '../html.ts';
import { speedsMarkup } from './speeds.ts';

export const sessionMarkup = (view: SessionSectionView, actionError: string | null = null, compact = false): Raw => {
  if (view.mode === 'non-local') return html`<div class="ws ws-session" id="ws" data-presentation="session" data-mode="non-local" style="height:${view.height}px"><div class="ws-line ws-nonlocal">${view.phase}</div></div>`;
  const scope = view.scope, alert = view.alert, progress = view.progress;
  if (compact) view = { ...view, height: view.height - 22 - (view.note ? 15 : 0) - (alert ? 6 : 0) };
  return html`<div class="ws ws-session" id="ws" data-presentation="session" data-mode="summary" style="height:${view.height}px"><dl class="speed-rows progress-row"><div class="speed-row" data-stage="progress" data-basis="${progress.basis}"><dt>Prompt progress</dt><dd title="${progress.detail}">${progress.text}<span class="sr-only basis">${progress.detail}</span></dd></div></dl>${speedsMarkup(view.speeds, true)}${!compact ? html`<div class="ws-line ws-heading ws-context"><span class="ws-phase" data-tone="${view.tone}">${view.phase}</span>${view.model ? html`<span class="ws-model" translate="no" title="${view.modelTitle ?? view.model}">${view.model}</span>` : ''}</div>` : ''}${scope ? html`<span class="ws-scope sr-only" data-attr="${scope.attr}">${scope.text}</span>` : ''}${view.note ? html`<div class="ws-note" title="${view.note}">${view.note}</div>` : ''}${alert ? html`<div class="ws-line ws-alert-row"><span class="ws-label" title="${alert.label}">${alert.label}</span><span class="ws-alert-value" data-severity="${alert.severity}">${alert.value}${alert.more ? html` <small>+${alert.more} more</small>` : ''}</span></div>` : ''}<div class="ws-actions"><button type="button" class="ws-details" data-action="${compact ? 'expand' : 'open-scope'}">${compact ? 'Expand' : 'Open MLX Scope'}</button>${view.cancelMeasurement ? html`<button type="button" class="ws-details" data-action="next-cancel">Cancel measurement</button>` : ''}</div>${actionError ? html`<p class="ws-action-error" id="ws-action-error" role="status">${actionError}</p>` : ''}</div>`;
};
